"""Generate pdfmath/fonts/data/tex_encodings.py from the AFM files of a TeX installation.

The encodings of the Computer Modern / AMS families are facts about the typefaces and do
not change; we extract them once and ship the table so that pdfmath works on machines
with no TeX installed.  Run with:  python tools/gen_encodings.py
"""
import subprocess, sys, os, pprint

# encoding-scheme name -> the AFM we take it from
SOURCES = {
    "OT1":   "cmr10.afm",      # text roman / sans / bold / slanted / italic / smallcaps
    "OT1TT": "cmtt10.afm",     # typewriter differs in several slots
    "OML":   "cmmi10.afm",     # TeX math italic
    "OMS":   "cmsy10.afm",     # TeX math symbols
    "OMX":   "cmex10.afm",     # TeX math extension
    "AMSA":  "msam10.afm",     # AMS symbols A
    "AMSB":  "msbm10.afm",     # AMS symbols B
    "EUFRAK": "eufm10.afm",    # Euler Fraktur
    "CMSS":  "cmss10.afm",
    "CMTI":  "cmti10.afm",
}


def kpse(name):
    try:
        p = subprocess.run(["kpsewhich", name], capture_output=True, text=True, timeout=20)
        path = p.stdout.strip()
        return path or None
    except Exception:
        return None


def parse_afm(path):
    """-> {code: (glyphname, width_1000, (llx,lly,urx,ury))}"""
    out = {}
    with open(path, "r", errors="replace") as fh:
        for line in fh:
            if not line.startswith("C "):
                continue
            fields = [f.strip() for f in line.split(";")]
            code = width = name = None
            bbox = None
            for f in fields:
                if f.startswith("C "):
                    code = int(f[2:])
                elif f.startswith("WX "):
                    width = float(f[3:])
                elif f.startswith("N "):
                    name = f[2:].strip()
                elif f.startswith("B "):
                    bbox = tuple(float(v) for v in f[2:].split())
            if code is not None and code >= 0 and name:
                out[code] = (name, width, bbox)
    return out


def main():
    tables = {}
    missing = []
    for scheme, afm in SOURCES.items():
        path = kpse(afm)
        if not path or not os.path.exists(path):
            missing.append((scheme, afm))
            continue
        tables[scheme] = {c: v[0] for c, v in sorted(parse_afm(path).items())}
    if missing:
        print("WARNING: could not locate:", missing, file=sys.stderr)

    dest = os.path.join(os.path.dirname(__file__), "..", "pdfmath", "fonts", "data",
                        "tex_encodings.py")
    with open(os.path.abspath(dest), "w") as fh:
        fh.write('"""TeX font encodings, generated by tools/gen_encodings.py.\n\n')
        fh.write("Do not edit by hand.  Maps encoding-scheme name -> {character code: glyph name}.\n")
        fh.write('Source: the AFM files shipped with the amsfonts Type 1 Computer Modern.\n"""\n\n')
        fh.write("# fmt: off\n")
        fh.write("ENCODINGS = ")
        pp = pprint.PrettyPrinter(indent=4, width=100)
        fh.write(pp.pformat(tables))
        fh.write("\n# fmt: on\n")
    for k, v in tables.items():
        print(f"{k}: {len(v)} slots")


if __name__ == "__main__":
    main()
