"""Fill gaps in the symbol table from LaTeXML's own command->Unicode declarations.

Our glyph table was written by hand from the Computer Modern layouts, which leaves the
AMS fonts thin: msam's ``square`` and msbm's ``lozenge`` have glyph names but no Unicode
and no atom class, so they arrive as Unknown.

LaTeXML ships the missing half as data::

    DefMath('\\square',  "\\x{25A1}");
    DefMath('\\boxplus', "\\x{229E}", role => 'ADDOP');

and we already know which glyph each command selects (latex/data/tex_commands.py, from
LaTeX's \\DeclareMathSymbol declarations).  Composing the two gives glyph -> Unicode and
glyph -> atom class for everything LaTeXML knows about, which is considerably more than
the Computer Modern layouts.

Run with:  python tools/gen_extra_symbols.py
"""
import glob
import os
import pprint
import re
import shutil
import subprocess
import sys

#: LaTeXML's grammatical role -> the TeX atom class it corresponds to.
ROLE_TO_ATOM = {
    "ADDOP": "BIN", "MULOP": "BIN", "BINOP": "BIN",
    "RELOP": "REL", "METARELOP": "REL", "ARROW": "REL",
    "OPEN": "OPEN", "CLOSE": "CLOSE", "PUNCT": "PUNCT",
    "BIGOP": "OP", "SUMOP": "OP", "INTOP": "OP", "OPERATOR": "OP",
    "ID": "ORD", "NUMBER": "ORD", "ATOM": "ORD", "UNKNOWN": "ORD",
}

#: Commands LaTeXML does not declare.  Its latexsym binding is empty -- the package's
#: symbols mostly duplicate amssymb ones under other names -- so the eleven that only
#: latexsym provides are listed here rather than left as Unknown.
FALLBACK = {
    "\\Box": ("\u25A1", "ORD"), "\\Diamond": ("\u25CA", "ORD"),
    "\\mho": ("\u2127", "ORD"), "\\leadsto": ("\u21DD", "REL"),
    "\\sqsubset": ("\u228F", "REL"), "\\sqsupset": ("\u2290", "REL"),
    "\\lhd": ("\u22B2", "BIN"), "\\rhd": ("\u22B3", "BIN"),
    "\\unlhd": ("\u22B4", "BIN"), "\\unrhd": ("\u22B5", "BIN"),
    "\\Join": ("\u22C8", "REL"),
}

_DEFMATH = re.compile(
    r"DefMath\(\s*'(\\[A-Za-z@]+)'\s*,\s*\"((?:\\x\{[0-9A-Fa-f]+\}|[^\"\\])+)\""
    r"(?P<rest>[^;]*)", re.S)
_ROLE = re.compile(r"role\s*=>\s*'([A-Z]+)'")
_HEX = re.compile(r"\\x\{([0-9A-Fa-f]+)\}")


def latexml_package_dir():
    exe = shutil.which("latexmlmath")
    if not exe:
        return None
    root = os.path.realpath(exe)
    for _ in range(6):
        root = os.path.dirname(root)
        found = glob.glob(os.path.join(root, "**", "LaTeXML", "Package"),
                          recursive=True)
        if found:
            return found[0]
    return None


def decode(literal):
    def sub(m):
        return chr(int(m.group(1), 16))
    return _HEX.sub(sub, literal)


def main():
    package = latexml_package_dir()
    if not package:
        print("LaTeXML not found; nothing to generate", file=sys.stderr)
        return 1
    pool = os.path.dirname(package)

    commands = {}
    files = sorted(glob.glob(os.path.join(package, "*.ltxml"))
                   + glob.glob(os.path.join(pool, "*.pool.ltxml")))
    for path in files:
        text = open(path, errors="replace").read()
        for m in _DEFMATH.finditer(text):
            cmd, literal, rest = m.group(1), m.group(2), m.group("rest")
            char = decode(literal)
            if not char or len(char) > 4:
                continue
            role = _ROLE.search(rest or "")
            atom = ROLE_TO_ATOM.get(role.group(1)) if role else None
            commands.setdefault(cmd, (char, atom))

    sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
    from pdfmath.fonts.symbols import lookup
    from pdfmath.latex.data.tex_commands import COMMAND_BY_GLYPH

    extra = {}
    for (enc, glyph), cmd in COMMAND_BY_GLYPH.items():
        if lookup(glyph).unicode:
            continue                    # our own table already knows this one
        entry = commands.get(cmd) or FALLBACK.get(cmd)
        if entry is None:
            continue
        char, atom = entry
        extra[(enc, glyph)] = (char, atom or "ORD")

    dest = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "pdfmath",
                                        "fonts", "data", "extra_symbols.py"))
    pp = pprint.PrettyPrinter(indent=4, width=94)
    with open(dest, "w") as fh:
        fh.write('"""Symbols our hand-written Computer Modern tables do not cover.\n\n')
        fh.write("Generated by tools/gen_extra_symbols.py from LaTeXML's DefMath\n")
        fh.write("declarations composed with LaTeX's \\\\DeclareMathSymbol tables.\n")
        fh.write("Maps (encoding, glyph name) -> (unicode, atom class name).\n")
        fh.write('Do not edit by hand.\n"""\n\n# fmt: off\nEXTRA_SYMBOLS = ')
        fh.write(pp.pformat(extra))
        fh.write("\n# fmt: on\n")
    print(f"{len(commands)} commands known to LaTeXML; {len(extra)} fill gaps -> {dest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
